### ISSUE TITLE
Alterações na Tabela de Colaboração

### ISSUE THREAD

**Issue by filipesaraiva** [Flaeury/AnyLattes#10]
Realizar as seguintes alterações na Tabela de Colaboração, na tela de Resultados Gerais:

- Adicionar uma coluna Estrato;
- Adicionar uma coluna listando o nome dos professores co-autores utilizando a mesma lógica da tabela de Relação das publicações (primeiro nome e último sobrenome);
- Alterar o nome da coluna Colaboradores para Mais Informações e colocar um ícone mais aproriado.

**Comment by Flaeury** [comment]
Colocar outra coluna pode não ser oportuna para o projeto, pouco espaço para por tanta informação, a própria tabela Relação das publicações já não se adapta bem a mudanças de tela. O ícone já consegue ser bastante explícito com relação ao dado que ele mostra.
