### ISSUE TITLE
Remoção da tela "Resultados por Docente"

### ISSUE THREAD

**Issue by filipesaraiva** [Flaeury/AnyLattes#20]
![image](https://github.com/Flaeury/AnyLattes/assets/203142/369631c0-f498-45a7-9c89-6bc6239a46a3)

Com a possibilidade de filtro por docente na tela _Resultado Geral_, vamos remover a tela _Resultados por Docente_ e todos os códigos relacionados a ela.

**Comment by filipesaraiva** [comment]
@Flaeury acabei de baixar o código e fazer o build, essa tela ainda está presente.

Verifique por favor, e quando for removido não remova apenas no frontend, remova os códigos também relacionados com essa tela.

**Comment by Flaeury** [comment]
Esta página contém funcionalidades que serão utilizadas eventualmente para a manutenção do projeto AnyLattes. De qualquer forma, irei excluir tudo da página e vou guardar as funções importantes em outro lugar.
